version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always

  app:
    build: .
    container_name: matchmaking_app
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - SERVER_PORT=${SERVER_PORT}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
    depends_on:
      - redis
